### ISSUE TITLE
Highlight all links on body click

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/wires#7]
This would simplify discovery of what's clickable. Similar to Sketch Cloud.

**Comment by AdrianMrn** [comment]
<img width="1003" alt="screenshot 2019-02-20 at 11 32 48" src="https://user-images.githubusercontent.com/12762044/53085487-4593d100-3503-11e9-981e-913b98994621.png">

**Comment by sebastiandedeyne** [comment]
Closed in favor of #8
